const hidraulico = [

    {
        foto: './img/abracadeira-tripartida-dn-50.jpg',
        codigo: '5401000829',
        busca: 'abracadeira',
        nome: 'Abraçadeira tripartida DN 50 mm segmentada sem dentes',
        material: 'Ferro fundido',
        dimensao: 'DN 50 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fanuel',
        unidade: 'peça',
        valor: 218.90,
        cor: ' ',
        fornecedor: 'Nelia Maria Cyrino',
        cidade: 'Murié - MG',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/colar-tomada-fofo.jpg',
        codigo: '5401001058',
        busca: 'colar de tomada',
        nome: 'Colar de tomada FOFO DN 75 mm X 3/4"',
        material: 'Ferro fundido',
        dimensao: 'DN 75 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'FM',
        unidade: 'peça',
        valor: 26.51,
        cor: ' ',
        fornecedor: 'G2 Materiais',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/colar-tomada-fofo.jpg',
        codigo: '5401001063',
        busca: 'colar de tomada',
        nome: 'Colar de tomada FOFO DN 250 mm X 3/4"',
        material: 'Ferro fundido',
        dimensao: 'DN 250 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'FM',
        unidade: 'peça',
        valor: 92.50,
        cor: ' ',
        fornecedor: 'G2 Materiais',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/estrangulador-pead.jpg',
        codigo: '5401002497',
        busca: 'estrangulador',
        nome: 'Estrangulador de tubo PEAD',
        material: 'Galvanizado',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Metalvax',
        unidade: 'unidade',
        valor: 96.25,
        cor: ' ',
        fornecedor: 'Metalvax',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/vareta-desobstrucao-esgoto.jpg',
        codigo: '5401003461',
        busca: 'vareta',
        nome: 'Jogo de varetas com acessórios para desobstrução de esgoto com acessórios',
        material: 'Aço temperado',
        dimensao: ' ',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'jogo 25 peças X 2 m',
        valor: 1900.00,
        cor: ' ',
        fornecedor: 'Fabricio Belizario',
        cidade: 'Sertãozinho - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn50.jpg',
        codigo: '5401002044',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X PVC DN 50/60 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 50/60 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 100.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tampao-esgoto-dn600.jpg',
        codigo: '5401001146',
        busca: 'tampao',
        nome: 'Tampão articulado fofo ductil',
        material: 'Ferro fundido',
        dimensao: 'DN 600 mm',
        classe: 'D-400',
        norma: 'NBR-10160',
        marca: 'Afer',
        unidade: 'peça',
        valor: 460.00,
        cor: ' ',
        fornecedor: 'Khaleesi',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tampao-agua-t05.jpg',
        codigo: '5401001144',
        busca: 'tampao',
        nome: 'Tampão articulado T-05',
        material: 'Ferro fundido',
        dimensao: ' ',
        classe: ' ',
        norma: ' ',
        marca: 'Afer',
        unidade: 'peça',
        valor: 108.00,
        cor: ' ',
        fornecedor: 'Khaleesi',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001980',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera 1/2"',
        material: 'Latão',
        dimensao: '1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 19.07,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001983',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera 3/4"',
        material: 'Latão',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 26.10,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001979',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera 1"',
        material: 'Latão',
        dimensao: '1"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 43.57,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-gaveta-cunha-borracha-bolsa-50.jpg',
        codigo: '5401002557',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha com bolsas DN 50 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '50 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 385.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/Valvula-gaveta-cunha-borracha-flangeada-100.jpg',
        codigo: '5401002004',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 100 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '100 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 550.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-gaveta-cunha-borracha-flageada-150.jpg',
        codigo: '5401002006',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 150 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 1073.33,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/Valvula-gaveta-cunha-borracha-flangeada-200.jpg',
        codigo: '5401003411',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 200 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '200 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 1400.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pead-azul.jpg',
        codigo: '5401001145',
        busca: 'tubo',
        nome: 'Tubo PEAD PE 80 PN 16 DE 20 mm',
        material: 'PEAD',
        dimensao: 'DE 20 mm X 2,3 mm',
        classe: 'PN 16',
        norma: 'NTS-048',
        marca: 'Asperbras',
        unidade: 'rolo (100 m)',
        valor: 318.30,
        cor: 'azul',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pead-azul.jpg',
        codigo: '5401001172',
        busca: 'tubo',
        nome: 'Tubo PEAD PE 80 PN 16 DE 32 mm',
        material: 'PEAD',
        dimensao: 'DE 32 mm X 3 mm',
        classe: 'PN 16',
        norma: 'NTS-048',
        marca: 'Asperbras',
        unidade: 'rolo (100 m)',
        valor: 357.00,
        cor: 'azul',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-branco-100.jpg',
        codigo: '5401001193',
        busca: 'tubo',
        nome: 'Tubo PVC branco DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'barra (6 m)',
        valor: 45.00,
        cor: 'branco',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-branco-roscavel.jpg',
        codigo: '5401002615',
        busca: 'tubo',
        nome: 'Tubo PVC branco roscável DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 19.23,
        cor: 'branco',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-marrom-soldavel.jpg',
        codigo: '5401002614',
        busca: 'tubo',
        nome: 'Tubo PVC marrom soldável DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 11.55,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-pba-75.jpg',
        codigo: '5401001168',
        busca: 'tubo',
        nome: 'Tubo PVC PBA JEI DN 60 mm classe 15',
        material: 'PVC PBA',
        dimensao: 'DN 60 mm',
        classe: '15',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 52.42,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-pba-75.jpg',
        codigo: '5401000638',
        busca: 'tubo',
        nome: 'Tubo PVC PBA JE DN 75 mm classe 20',
        material: 'PVC PBA',
        dimensao: 'DN 75 mm',
        classe: '20',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 134.61,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-ocre-100.jpg',
        codigo: '5401000916',
        busca: 'tubo',
        nome: 'Tubo PVC ocre liso DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 211.00,
        cor: 'ocre',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-ocre-150.jpg',
        codigo: '5401000509',
        busca: 'tubo',
        nome: 'Tubo PVC ocre liso DN 150 mm',
        material: 'PVC',
        dimensao: 'DN 150 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6m)',
        valor: 161.50,
        cor: 'ocre',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    }

]

function carregarLista() {
    let conteudo = document.getElementById('conteudo');

    for(let i = 0; i < hidraulico.length; i++){
        conteudo.innerHTML += `<div>
                                <img src=${hidraulico[i].foto}>
                                <p>Cod.: <strong>${hidraulico[i].codigo}</strong>
                                <br>${hidraulico[i].nome}
                                <br>${hidraulico[i].material}
                                <br>Medida: ${hidraulico[i].dimensao}
                                <br>Classe: ${hidraulico[i].classe}
                                <br>Norma: ${hidraulico[i].norma}
                                <br>Marca: ${hidraulico[i].marca}
                                <br>Unidade: ${hidraulico[i].unidade}
                                <br>Preço: ${hidraulico[i].valor.toLocaleString('pt-br', {style: 'currency', currency: 'BRL'})}
                                <br>Fornecedor: ${hidraulico[i].fornecedor}
                                </p>
                                </div>`;
    }
}
