const hidraulico = [

    {
        foto: './img/abracadeira-tripartida-dn-50.jpg',
        codigo: '5401000829',
        busca: 'abracadeira',
        nome: 'Abraçadeira tripartida DN 50 mm segmentada sem dentes',
        material: 'Ferro fundido',
        dimensao: 'DN 50 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fanuel',
        unidade: 'peça',
        valor: 218.90,
        cor: ' ',
        fornecedor: 'Nelia Maria Cyrino',
        cidade: 'Murié - MG',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-latao.jpg',
        codigo: '5401002470',
        busca: 'bucha',
        nome: 'Bucha de redução em latão 1" X 3/4" BSP',
        material: 'Latão',
        dimensao: 'DN 1" X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Ramo',
        unidade: 'unidade',
        valor: 14.21,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-pvc.jpg',
        codigo: '5401002472',
        busca: 'bucha',
        nome: 'Bucha de redução PVC 1" X 3/4" BSP',
        material: 'PVC',
        dimensao: 'DN 1" X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 1.70,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/colar-tomada-fofo.jpg',
        codigo: '5401001058',
        busca: 'colar de tomada',
        nome: 'Colar de tomada FOFO DN 75 mm X 3/4"',
        material: 'Ferro fundido',
        dimensao: 'DN 75 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'FM',
        unidade: 'peça',
        valor: 26.51,
        cor: ' ',
        fornecedor: 'G2 Materiais',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/colar-tomada-fofo.jpg',
        codigo: '5401001063',
        busca: 'colar de tomada',
        nome: 'Colar de tomada FOFO DN 250 mm X 3/4"',
        material: 'Ferro fundido',
        dimensao: 'DN 250 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'FM',
        unidade: 'peça',
        valor: 92.50,
        cor: ' ',
        fornecedor: 'G2 Materiais',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-latao.jpg',
        codigo: '5401001069',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º latão 1"',
        material: 'Latão',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 24.00,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-pvc-branco-esgoto-dn100.jpg',
        codigo: '5401002071',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º PVC branco esgoto DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 3.80,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-pvc-branco-rosca-anel-metalico.jpg',
        codigo: '5401000782',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º PVC branco rosca com anel metálico 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 2.40,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/curva-45-pvc-branco-esgoto.jpg',
        codigo: '5401002877',
        busca: 'curva',
        nome: 'Curva 45º PVC branco esgoto DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 27.50,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/curva-90-pvc-branco-esgoto.jpg',
        codigo: '5401002876',
        busca: 'curva',
        nome: 'Curva 90º PVC branco esgoto DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 13.80,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/estrangulador-pead.jpg',
        codigo: '5401002497',
        busca: 'estrangulador',
        nome: 'Estrangulador de tubo PEAD',
        material: 'Galvanizado',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Metalvax',
        unidade: 'unidade',
        valor: 96.25,
        cor: ' ',
        fornecedor: 'Metalvax',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/vareta-desobstrucao-esgoto.jpg',
        codigo: '5401003461',
        busca: 'vareta',
        nome: 'Jogo de varetas com acessórios para desobstrução de esgoto com acessórios',
        material: 'Aço temperado',
        dimensao: ' ',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'jogo 25 peças X 2 m',
        valor: 1900.00,
        cor: ' ',
        fornecedor: 'Fabricio Belizario',
        cidade: 'Sertãozinho - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn50.jpg',
        codigo: '5401002576',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X PVC DN 50/60 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 50/60 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 100.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn50.jpg',
        codigo: '5401002044',
        busca: 'gibault',
        nome: 'Junta gibault PVC X PVC DN 60 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 60 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 100.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn150.jpg',
        codigo: '5401000819',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X FOFO DN 150 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 150 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 160.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn200.jpg',
        codigo: '5401000820',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X FOFO DN 200 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 200 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 230.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/lacre-plastico-azul.jpg',
        codigo: '5401001101',
        busca: 'lacre',
        nome: 'Lacre de plástico para hidrômetro azul',
        material: 'plástico',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 0.59,
        cor: 'azul',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/lacre-plastico-vemelho.jpg',
        codigo: '5401002230',
        busca: 'lacre',
        nome: 'Lacre de plástico para hidrômetro vermelho',
        material: 'plástico',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 0.59,
        cor: 'vermeho',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/lacre-seguranca-arame.jpg',
        codigo: '5401003044',
        busca: 'lacre',
        nome: 'Lacre de segurança com trava em arame',
        material: 'poliestireno e arame galvanizado',
        dimensao: '1,20 m',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 1.79,
        cor: 'azul',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-correr-pvc-branco-esgoto.jpg',
        codigo: '5401001114',
        busca: 'luva',
        nome: 'Luva de correr PVC branco esgoto JERI DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'CAM',
        unidade: 'peça',
        valor: 4.90,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-latao.jpg',
        codigo: '5401000792',
        busca: 'luva',
        nome: 'Luva latão 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 12.00,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-pvc-branco.jpg',
        codigo: '5401000729',
        busca: 'luva',
        nome: 'Luva união PVC branco 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 5.50,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-latao.jpg',
        codigo: '5401000613',
        busca: 'niple',
        nome: 'Niple latão 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 10.99,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-latao.jpg',
        codigo: '5401000226',
        busca: 'niple',
        nome: 'Niple latão 1"',
        material: 'Latão',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'Ramo',
        unidade: 'unidade',
        valor: 18.02,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/obstrutor-cavalete.jpeg',
        codigo: '5401001127',
        busca: 'obstrutor',
        nome: 'Obstrutor de cavalete com porca sextavada e ponta macho em latão 3/4"',
        material: 'latão',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 3.22,
        cor: '',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tampao-esgoto-dn600.jpg',
        codigo: '5401001146',
        busca: 'tampao',
        nome: 'Tampão articulado fofo ductil DN 600 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 600 mm',
        classe: 'D-400',
        norma: 'NBR-10160',
        marca: 'Afer',
        unidade: 'peça',
        valor: 460.00,
        cor: ' ',
        fornecedor: 'Khaleesi',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tampao-agua-t05.jpg',
        codigo: '5401001144',
        busca: 'tampao',
        nome: 'Tampão articulado T-05',
        material: 'Ferro fundido',
        dimensao: ' ',
        classe: ' ',
        norma: ' ',
        marca: 'Afer',
        unidade: 'peça',
        valor: 108.00,
        cor: ' ',
        fornecedor: 'Khaleesi',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-latao.jpg',
        codigo: '5401000789',
        busca: 'te',
        nome: 'Te Latão 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 20.01,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pead-azul.jpg',
        codigo: '5401001145',
        busca: 'tubo',
        nome: 'Tubo PEAD PE 80 PN 16 DE 20 mm',
        material: 'PEAD',
        dimensao: 'DE 20 mm X 2,3 mm',
        classe: 'PN 16',
        norma: 'NTS-048',
        marca: 'Asperbras',
        unidade: 'rolo (100 m)',
        valor: 318.30,
        cor: 'azul',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pead-azul.jpg',
        codigo: '5401001172',
        busca: 'tubo',
        nome: 'Tubo PEAD PE 80 PN 16 DE 32 mm',
        material: 'PEAD',
        dimensao: 'DE 32 mm X 3 mm',
        classe: 'PN 16',
        norma: 'NTS-048',
        marca: 'Asperbras',
        unidade: 'rolo (100 m)',
        valor: 357.00,
        cor: 'azul',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-branco-100.jpg',
        codigo: '5401001193',
        busca: 'tubo',
        nome: 'Tubo PVC branco DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'barra (6 m)',
        valor: 45.00,
        cor: 'branco',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-branco-roscavel.jpg',
        codigo: '5401002615',
        busca: 'tubo',
        nome: 'Tubo PVC branco roscável DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 19.23,
        cor: 'branco',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-marrom-soldavel.jpg',
        codigo: '5401002614',
        busca: 'tubo',
        nome: 'Tubo PVC marrom soldável DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 11.55,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-pba-75.jpg',
        codigo: '5401001168',
        busca: 'tubo',
        nome: 'Tubo PVC PBA JEI DN 60 mm classe 15',
        material: 'PVC PBA',
        dimensao: 'DN 60 mm',
        classe: '15',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 52.42,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-pba-75.jpg',
        codigo: '5401000638',
        busca: 'tubo',
        nome: 'Tubo PVC PBA JE DN 75 mm classe 20',
        material: 'PVC PBA',
        dimensao: 'DN 75 mm',
        classe: '20',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 134.61,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-ocre-100.jpg',
        codigo: '5401000916',
        busca: 'tubo',
        nome: 'Tubo PVC ocre liso DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 211.00,
        cor: 'ocre',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-ocre-150.jpg',
        codigo: '5401000509',
        busca: 'tubo',
        nome: 'Tubo PVC ocre liso DN 150 mm',
        material: 'PVC',
        dimensao: 'DN 150 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6m)',
        valor: 161.50,
        cor: 'ocre',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-borboleta-tipo-wafer-dn150.jpg',
        codigo: '5401002549',
        busca: 'valvula',
        nome: 'Válvula borboleta tipo wafer DN 150 mm PN 10',
        material: 'ferro fundido',
        dimensao: '150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'VARB',
        unidade: 'unidade',
        valor: 506.30,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001980',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera 1/2"',
        material: 'Latão',
        dimensao: '1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 19.07,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001983',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera 3/4"',
        material: 'Latão',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 26.10,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001979',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera 1"',
        material: 'Latão',
        dimensao: '1"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 43.57,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-gaveta-cunha-borracha-bolsa-50.jpg',
        codigo: '5401002557',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha com bolsas DN 50 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '50 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 385.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/Valvula-gaveta-cunha-borracha-flangeada-100.jpg',
        codigo: '5401002004',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 100 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '100 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 550.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-gaveta-cunha-borracha-flageada-150.jpg',
        codigo: '5401002006',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 150 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 1073.33,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/Valvula-gaveta-cunha-borracha-flangeada-200.jpg',
        codigo: '5401003411',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 200 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: '200 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 1400.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-gaveta-roscavel.jpg',
        codigo: '5401002353',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta roscável 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Remadi',
        unidade: 'unidade',
        valor: 29.40,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-retencao-portinhola-dupla.jpg',
        codigo: '5401001188',
        busca: 'valvula',
        nome: 'Válvula de retenção portinhola dupla DN 100 mm',
        material: 'ferro fundido',
        dimensao: '100 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'VARB',
        unidade: 'peça',
        valor: 495.92,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-retencao-portinhola-dupla.jpg',
        codigo: '5401001189',
        busca: 'valvula',
        nome: 'Válvula de retenção portinhola dupla DN 150 mm',
        material: 'ferro fundido',
        dimensao: '150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'VARB',
        unidade: 'peça',
        valor: 788.42,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-retencao-portinhola-dupla.jpg',
        codigo: '5401001186',
        busca: 'valvula',
        nome: 'Válvula de retenção portinhola dupla DN 400 mm',
        material: 'ferro fundido',
        dimensao: '400 mm',
        classe: 'PN 10 / PN 16',
        norma: ' ',
        marca: 'VARB',
        unidade: 'peça',
        valor: 6074.24,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    }

]

function carregarLista() {
    let conteudo = document.getElementById('conteudo');

    for(let i = 0; i < hidraulico.length; i++){
        conteudo.innerHTML += `<div>
                                <img src=${hidraulico[i].foto}>
                                <p>Cod.: <strong>${hidraulico[i].codigo}</strong>
                                <br>${hidraulico[i].nome}
                                <br>Material: ${hidraulico[i].material}
                                <br>Medida: ${hidraulico[i].dimensao}
                                <br>Classe: ${hidraulico[i].classe}
                                <br>Norma: ${hidraulico[i].norma}
                                <br>Marca: ${hidraulico[i].marca}
                                <br>Unidade: ${hidraulico[i].unidade}
                                <br>Preço: ${hidraulico[i].valor.toLocaleString('pt-br', {style: 'currency', currency: 'BRL'})}
                                <br>Fornecedor: ${hidraulico[i].fornecedor}
                                </p>
                                </div>`;
    }
}
