const hidraulico = [

    {
        foto: './img/abracadeira-tripartida-dn-50.jpg',
        codigo: '5401000829',
        busca: 'abracadeira',
        nome: 'Abraçadeira tripartida DN 50 mm segmentada sem dentes',
        material: 'Ferro fundido',
        dimensao: 'DN 50 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fanuel',
        unidade: 'peça',
        valor: 218.90,
        cor: ' ',
        fornecedor: 'Nelia Maria Cyrino',
        cidade: 'Murié - MG',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/adaptador-compressao-pead.jpg',
        codigo: '5401002447',
        busca: 'adaptador',
        nome: 'Adaptador de compressão PEAD DN 20 mm X 3/4"',
        material: 'PEAD',
        dimensao: 'DN 20 mm X 3/4"',
        classe: ' ',
        norma: 'NTS-179',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 2.00,
        cor: ' ',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/adaptador-compressao-pead.jpg',
        codigo: '5401002448',
        busca: 'adaptador',
        nome: 'Adaptador de compressão PEAD DN 32 mm X 1"',
        material: 'PEAD',
        dimensao: 'DN 32 mm X 1"',
        classe: ' ',
        norma: 'NTS-179',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 4.49,
        cor: ' ',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/adaptador-compressao-pead-rosca-interna.jpg',
        codigo: '5401003305',
        busca: 'adaptador',
        nome: 'Adaptador de compressão PEAD DN 20 mm X 3/4" com rosca interna',
        material: 'PEAD',
        dimensao: 'DN 20 mm X 3/4"',
        classe: ' ',
        norma: 'NTS-179',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 2.00,
        cor: ' ',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-latao.jpg',
        codigo: '5401002470',
        busca: 'bucha',
        nome: 'Bucha de redução em latão DN 1" X 3/4" BSP',
        material: 'Latão',
        dimensao: 'DN 1" X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Ramo',
        unidade: 'unidade',
        valor: 14.21,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401002467',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 1/2" X 1/4"',
        material: 'Galvanizado',
        dimensao: 'DN 1/2" X 1/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 2.83,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401000420',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 3/4" X 1/4"',
        material: 'Galvanizado',
        dimensao: 'DN 3/4" X 1/4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 2.65,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401000420',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 2" X 1"',
        material: 'Galvanizado',
        dimensao: 'DN 2" X 1"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 13.09,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401002573',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 3" X 2"',
        material: 'Galvanizado',
        dimensao: 'DN 3" X 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 32.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401000420',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 3" X 2 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 3" X 2 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 30.90,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401003947',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 4" X 2"',
        material: 'Galvanizado',
        dimensao: 'DN 4" X 2"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 62.50,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-galvanizado-bsp.jpg',
        codigo: '5401000803',
        busca: 'bucha',
        nome: 'Bucha de redução galvanizado BSP DN 4" X 3"',
        material: 'Galvanizado',
        dimensao: 'DN 4" X 3"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 61.50,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/bucha-reducao-pvc.jpg',
        codigo: '5401002472',
        busca: 'bucha',
        nome: 'Bucha de redução PVC DN 1" X 3/4" BSP',
        material: 'PVC',
        dimensao: 'DN 1" X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 1.70,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cap-galvanizado.jpg',
        codigo: '5401003949',
        busca: 'cap',
        nome: 'Cap galvanizado rosca DN 1 1/4"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 7.95,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cap-galvanizado.jpg',
        codigo: '5401003948',
        busca: 'cap',
        nome: 'Cap galvanizado rosca DN 1 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 9.50,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cap-galvanizado.jpg',
        codigo: '5401003950',
        busca: 'cap',
        nome: 'Cap galvanizado rosca DN 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 12.90,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cap-galvanizado.jpg',
        codigo: '5401003951',
        busca: 'cap',
        nome: 'Cap galvanizado rosca DN 2 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 26.50,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cap-galvanizado.jpg',
        codigo: '5401000427',
        busca: 'cap',
        nome: 'Cap galvanizado DN 3"',
        material: 'Galvanizado',
        dimensao: 'DN 3"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 35.85,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cap-galvanizado.jpg',
        codigo: '5401003952',
        busca: 'cap',
        nome: 'Cap galvanizado rosca DN 4"',
        material: 'Galvanizado',
        dimensao: 'DN 4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 62.90,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/colar-tomada-fofo.jpg',
        codigo: '5401001058',
        busca: 'colar de tomada',
        nome: 'Colar de tomada FOFO DN 75 mm X 3/4"',
        material: 'Ferro fundido',
        dimensao: 'DN 75 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'FM',
        unidade: 'peça',
        valor: 26.51,
        cor: ' ',
        fornecedor: 'G2 Materiais',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/colar-tomada-fofo.jpg',
        codigo: '5401001063',
        busca: 'colar de tomada',
        nome: 'Colar de tomada FOFO DN 250 mm X 3/4"',
        material: 'Ferro fundido',
        dimensao: 'DN 250 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'FM',
        unidade: 'peça',
        valor: 92.50,
        cor: ' ',
        fornecedor: 'G2 Materiais',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-femea-adaptador-pead.jpg',
        codigo: '5401003353',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º fêmea  adapatador PEAD DN 20 mm X 3/4" PN 16',
        material: 'PEAD',
        dimensao: 'DN 20 mm X 3/4"',
        classe: 'PN 16',
        norma: 'NTS-179',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 2.00,
        cor: ' ',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-galvanizado-bsp.jpg',
        codigo: '5401000809',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º galvanizado BSP DN 1 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'peça',
        valor: 15.40,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-galvanizado-bsp.jpg',
        codigo: '5401000810',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º galvanizado BSP DN 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'peça',
        valor: 23.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-galvanizado-bsp.jpg',
        codigo: '5401003953',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º galvanizado BSP DN 2 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'peça',
        valor: 44.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },


    {
        foto: './img/cotovelo-90-galvanizado-bsp.jpg',
        codigo: '5401000811',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º galvanizado BSP DN 3"',
        material: 'Galvanizado',
        dimensao: 'DN 3"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'peça',
        valor: 65.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-galvanizado-bsp.jpg',
        codigo: '5401000812',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º galvanizado BSP DN 4"',
        material: 'Galvanizado',
        dimensao: 'DN 4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'peça',
        valor: 118.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-latao.jpg',
        codigo: '5401001069',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º latão DN 1"',
        material: 'Latão',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 24.00,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-pead.jpg',
        codigo: '5401003356',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º PEAD DN 20 mm PN 16',
        material: 'PEAD',
        dimensao: 'DN 20 mm',
        classe: 'PN 16',
        norma: 'NTS-179',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 3.50,
        cor: ' ',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-pvc-branco-esgoto-dn100.jpg',
        codigo: '5401002071',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º PVC branco esgoto DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 3.80,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/cotovelo-90-pvc-branco-rosca-anel-metalico.jpg',
        codigo: '5401000782',
        busca: 'cotovelo',
        nome: 'Cotovelo 90º PVC branco rosca com anel metálico DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 2.40,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/curva-45-pvc-branco-esgoto.jpg',
        codigo: '5401002877',
        busca: 'curva',
        nome: 'Curva 45º PVC branco esgoto DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 27.50,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/curva-90-pvc-branco-esgoto.jpg',
        codigo: '5401002876',
        busca: 'curva',
        nome: 'Curva 90º PVC branco esgoto DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 13.80,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/estrangulador-pead.jpg',
        codigo: '5401002497',
        busca: 'estrangulador',
        nome: 'Estrangulador de tubo PEAD',
        material: 'Galvanizado',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Metalvax',
        unidade: 'unidade',
        valor: 96.25,
        cor: ' ',
        fornecedor: 'Metalvax',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/vareta-desobstrucao-esgoto.jpg',
        codigo: '5401003461',
        busca: 'vareta',
        nome: 'Jogo de varetas com acessórios para desobstrução de esgoto com acessórios',
        material: 'Aço temperado',
        dimensao: ' ',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'jogo 25 peças X 2 m',
        valor: 1900.00,
        cor: ' ',
        fornecedor: 'Fabricio Belizario',
        cidade: 'Sertãozinho - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn50.jpg',
        codigo: '5401002576',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X PVC DN 50/60 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 50/60 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 100.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn50.jpg',
        codigo: '5401002044',
        busca: 'gibault',
        nome: 'Junta gibault PVC X PVC DN 60 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 60 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 100.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn150.jpg',
        codigo: '5401000819',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X FOFO DN 150 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 150 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 160.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/junta-gibault-dn200.jpg',
        codigo: '5401000820',
        busca: 'gibault',
        nome: 'Junta gibault FOFO X FOFO DN 200 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 200 mm',
        classe: ' ',
        norma: ' ',
        marca: 'marca própria',
        unidade: 'peça',
        valor: 230.00,
        cor: ' ',
        fornecedor: 'VAL do Prado',
        cidade: 'São José do Rio Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/lacre-plastico-azul.jpg',
        codigo: '5401001101',
        busca: 'lacre',
        nome: 'Lacre de plástico para hidrômetro azul 3/4"',
        material: 'plástico',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 0.59,
        cor: 'azul',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/lacre-plastico-vemelho.jpg',
        codigo: '5401002230',
        busca: 'lacre',
        nome: 'Lacre de plástico para hidrômetro vermelho 3/4"',
        material: 'plástico',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 0.59,
        cor: 'vermeho',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/lacre-seguranca-arame.jpg',
        codigo: '5401003044',
        busca: 'lacre',
        nome: 'Lacre de segurança com trava em arame',
        material: 'poliestireno e arame galvanizado',
        dimensao: '1,20 m',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 1.79,
        cor: 'azul',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-correr-pvc-branco-esgoto.jpg',
        codigo: '5401001114',
        busca: 'luva',
        nome: 'Luva de correr PVC branco esgoto JERI DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'CAM',
        unidade: 'peça',
        valor: 4.90,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-reducao.jpg',
        codigo: '5401003954',
        busca: 'luva',
        nome: 'Luva de redução galvanizada BSP DN 2 1/2" X 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/2" X 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 33.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-reducao.jpg',
        codigo: '5401003955',
        busca: 'luva',
        nome: 'Luva de redução galvanizada BSP DN 2" X 1"',
        material: 'Galvanizado',
        dimensao: 'DN 2" X 1"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 18.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-reducao.jpg',
        codigo: '5401003956',
        busca: 'luva',
        nome: 'Luva de redução galvanizada BSP DN 4" X 2"',
        material: 'Galvanizado',
        dimensao: 'DN 4" X 2"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 79.00,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-reducao.jpg',
        codigo: '5401003957',
        busca: 'luva',
        nome: 'Luva de redução galvanizada BSP DN 4" X 3"',
        material: 'Galvanizado',
        dimensao: 'DN 4" X 3"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 83.85,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-galvanizada-roscavel-bsp.jpg',
        codigo: '5401003958',
        busca: 'luva',
        nome: 'Luva galvanizada roscável BSP DN 3/4"',
        material: 'Galvanizado',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 3.80,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-galvanizada-roscavel-bsp.jpg',
        codigo: '5401003959',
        busca: 'luva',
        nome: 'Luva galvanizada roscável BSP DN 1 1/4"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 9.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-galvanizada-roscavel-bsp.jpg',
        codigo: '5401003960',
        busca: 'luva',
        nome: 'Luva galvanizada roscável BSP DN 2 1/4"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 31.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-latao.jpg',
        codigo: '5401000792',
        busca: 'luva',
        nome: 'Luva latão DN 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 12.00,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-galvanizado.jpg',
        codigo: '5401001116',
        busca: 'luva',
        nome: 'Luva de de união galvanizada BSP DN 1 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 32.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-galvanizado.jpg',
        codigo: '5401000397',
        busca: 'luva',
        nome: 'Luva de de união galvanizada BSP DN 1"',
        material: 'Galvanizado',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 17.50,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-galvanizado.jpg',
        codigo: '5401000791',
        busca: 'luva',
        nome: 'Luva de de união galvanizada BSP DN 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 45.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-galvanizado.jpg',
        codigo: '5401002066',
        busca: 'luva',
        nome: 'Luva de de união galvanizada BSP DN 3"',
        material: 'Galvanizado',
        dimensao: 'DN 3"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 127.50,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-pvc-branco.jpg',
        codigo: '5401000729',
        busca: 'luva',
        nome: 'Luva união PVC branco DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 5.50,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/luva-uniao-pvc-branco.jpg',
        codigo: '5401002516',
        busca: 'luva',
        nome: 'Luva união roscável PVC branco DN 2"',
        material: 'PVC',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'unidade',
        valor: 39.60,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-reducao-latao.jpg',
        codigo: '5401000964',
        busca: 'niple',
        nome: 'Niple de redução latão DN 1" X 3/4"',
        material: 'Galvanizado',
        dimensao: 'DN 1" X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 9.50,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401002517',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 1/4"',
        material: 'Galvanizado',
        dimensao: 'DN 1/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 3.10,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401003961',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 2.45,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401001126',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 1 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 10.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401003135',
        busca: 'niple',
        nome: 'Niple duplo galvanizado DN 1"',
        material: 'Galvanizado',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 5.50,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401003962',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 2 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 26.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401000794',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 16.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401000795',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 3"',
        material: 'Galvanizado',
        dimensao: 'DN 3"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 40.00,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-galvanizado-bsp.jpg',
        codigo: '5401000796',
        busca: 'niple',
        nome: 'Niple galvanizado BSP DN 4"',
        material: 'Galvanizado',
        dimensao: 'DN 4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 64.70,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-latao.jpg',
        codigo: '5401000613',
        busca: 'niple',
        nome: 'Niple latão DN 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 10.99,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-latao.jpg',
        codigo: '5401000226',
        busca: 'niple',
        nome: 'Niple latão DN 1"',
        material: 'Latão',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'Ramo',
        unidade: 'unidade',
        valor: 18.02,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-pvc.jpeg',
        codigo: '5401000758',
        busca: 'niple',
        nome: 'Niple PVC DN 1/2"',
        material: 'PVC',
        dimensao: 'DN 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 0.30,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/niple-pvc.jpeg',
        codigo: '54010007589',
        busca: 'niple',
        nome: 'Niple PVC DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 0.80,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/obstrutor-cavalete.jpeg',
        codigo: '5401001127',
        busca: 'obstrutor',
        nome: 'Obstrutor de cavalete com porca sextavada e ponta macho em latão 3/4"',
        material: 'latão',
        dimensao: '3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Vedasystem',
        unidade: 'unidade',
        valor: 3.22,
        cor: '',
        fornecedor: 'Youcare',
        cidade: 'Barueri - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/porca-tubete-pvc.jpg',
        codigo: '5401000616',
        busca: 'porca',
        nome: 'Porca para tubete preto 3/4"',
        material: 'PEAD',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 1.00,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/porca-tubete-pvc-inserto.jpg',
        codigo: '5401001129',
        busca: 'porca',
        nome: 'Porca para tubete preto 3/4" com inserto metálico',
        material: 'PEAD',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 2.00,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401000806',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 2.10,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401002579',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 3/4"',
        material: 'Galvanizado',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 2.50,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401000804',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 1"',
        material: 'Galvanizado',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 3.35,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401003448',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 1 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 6.40,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401003963',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 9.85,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401003964',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 2 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 20.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401003965',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 3"',
        material: 'Galvanizado',
        dimensao: 'DN 3"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 28.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-galvanizado-bsp.jpg',
        codigo: '5401003966',
        busca: 'plug',
        nome: 'Plug galvanizado BSP DN 4"',
        material: 'Galvanizado',
        dimensao: 'DN 4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 50.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/plug-pvc-branco-rosca.jpeg',
        codigo: '5401001128',
        busca: 'plug',
        nome: 'Plug PVC branco rosca DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'peça',
        valor: 0.70,
        cor: 'branco',
        fornecedor: 'N. S. A. Comércio',
        cidade: 'Curitiba - PR',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tampao-esgoto-dn600.jpg',
        codigo: '5401001146',
        busca: 'tampao',
        nome: 'Tampão articulado fofo ductil DN 600 mm',
        material: 'Ferro fundido',
        dimensao: 'DN 600 mm',
        classe: 'D-400',
        norma: 'NBR-10160',
        marca: 'Afer',
        unidade: 'peça',
        valor: 460.00,
        cor: ' ',
        fornecedor: 'Khaleesi',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tampao-agua-t05.jpg',
        codigo: '5401001144',
        busca: 'tampao',
        nome: 'Tampão articulado T-05',
        material: 'Ferro fundido',
        dimensao: ' ',
        classe: ' ',
        norma: ' ',
        marca: 'Afer',
        unidade: 'peça',
        valor: 108.00,
        cor: ' ',
        fornecedor: 'Khaleesi',
        cidade: 'São Paulo - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-compressao-pead-y.jpg',
        codigo: '5401001921',
        busca: 'te',
        nome: 'Te de compresão em PP/PEAD em Y DN 20 mm X 3/4"',
        material: 'PEAD',
        dimensao: 'DN 20 mm X 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Doal PLastic',
        unidade: 'unidade',
        valor: 11.50,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-servico-integrado-articulado.jpg',
        codigo: '5401000988',
        busca: 'te',
        nome: 'Te de serviço integrado articulado DN 60 mm X 20 mm PN 16 NTS 175',
        material: 'PEAD',
        dimensao: 'DN 60 mm X 20 mm',
        classe: 'PN 16',
        norma: 'NBR-15803',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 13.00,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-servico-integrado-articulado.jpg',
        codigo: '5401003427',
        busca: 'te',
        nome: 'Te de serviço integrado articulado DN 63 mm X 20 mm NTS 175',
        material: 'PEAD',
        dimensao: 'DN 63 mm X 20 mm',
        classe: ' ',
        norma: 'NBR-15803',
        marca: 'Polierg',
        unidade: 'unidade',
        valor: 30.00,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-galvanizado-bsp.jpg',
        codigo: '5401001153',
        busca: 'te',
        nome: 'Te galvanizado BSP DN 1 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 1 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 20.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-galvanizado-bsp.jpg',
        codigo: '5401002067',
        busca: 'te',
        nome: 'Te galvanizado BSP DN 2"',
        material: 'Galvanizado',
        dimensao: 'DN 2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 30.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-galvanizado-bsp.jpg',
        codigo: '5401003967',
        busca: 'te',
        nome: 'Te galvanizado BSP DN 2 1/2"',
        material: 'Galvanizado',
        dimensao: 'DN 2 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 59.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-galvanizado-bsp.jpg',
        codigo: '5401003968',
        busca: 'te',
        nome: 'Te galvanizado BSP DN 3"',
        material: 'Galvanizado',
        dimensao: 'DN 3"',
        classe: ' ',
        norma: ' ',
        marca: 'Tupy',
        unidade: 'unidade',
        valor: 78.00,
        cor: ' ',
        fornecedor: 'Forthy',
        cidade: 'Porto Feliz - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-galvanizado-bsp.jpg',
        codigo: '5401003969',
        busca: 'te',
        nome: 'Te galvanizado BSP DN 4"',
        material: 'Galvanizado',
        dimensao: 'DN 4"',
        classe: ' ',
        norma: ' ',
        marca: 'GIPP',
        unidade: 'unidade',
        valor: 140.00,
        cor: ' ',
        fornecedor: 'Vitoria Scaldelai',
        cidade: 'Catanduva - SP',
        prazo: '30 dias',
        vigencia: '29/11/2024',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/te-latao.jpg',
        codigo: '5401000789',
        busca: 'te',
        nome: 'Te Latão DN 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Belmar',
        unidade: 'peça',
        valor: 20.01,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubete-longo-preto-rosca-curta.jpg',
        codigo: '5401002063',
        busca: 'tubete',
        nome: 'Tubete longo preto com rosca curta PP DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 1.14,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubete-pvc-rosca-estendida.jpg',
        codigo: '5401002526',
        busca: 'tubete',
        nome: 'Tubete PVC com rosca estendida 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 2.20,
        cor: 'azul',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubete-pvc-curto.jpg',
        codigo: '5401000773',
        busca: 'tubete',
        nome: 'Tubete PVC preto curto DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'ESSA',
        unidade: 'unidade',
        valor: 0.50,
        cor: 'preto',
        fornecedor: 'Hidrotam',
        cidade: 'Serra - ES',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pead-azul.jpg',
        codigo: '5401001145',
        busca: 'tubo',
        nome: 'Tubo PEAD PE 80 PN 16 DE 20 mm',
        material: 'PEAD',
        dimensao: 'DE 20 mm X 2,3 mm',
        classe: 'PN 16',
        norma: 'NTS-048',
        marca: 'Asperbras',
        unidade: 'rolo (100 m)',
        valor: 318.30,
        cor: 'azul',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pead-azul.jpg',
        codigo: '5401001172',
        busca: 'tubo',
        nome: 'Tubo PEAD PE 80 PN 16 DE 32 mm',
        material: 'PEAD',
        dimensao: 'DE 32 mm X 3 mm',
        classe: 'PN 16',
        norma: 'NTS-048',
        marca: 'Asperbras',
        unidade: 'rolo (100 m)',
        valor: 357.00,
        cor: 'azul',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-branco-100.jpg',
        codigo: '5401001193',
        busca: 'tubo',
        nome: 'Tubo PVC branco DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Plastilit',
        unidade: 'barra (6 m)',
        valor: 45.00,
        cor: 'branco',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-branco-roscavel.jpg',
        codigo: '5401002615',
        busca: 'tubo',
        nome: 'Tubo PVC branco roscável DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 19.23,
        cor: 'branco',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-marrom-soldavel.jpg',
        codigo: '5401002614',
        busca: 'tubo',
        nome: 'Tubo PVC marrom soldável DN 3/4"',
        material: 'PVC',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 11.55,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-pba-75.jpg',
        codigo: '5401001168',
        busca: 'tubo',
        nome: 'Tubo PVC PBA JEI DN 60 mm classe 15',
        material: 'PVC PBA',
        dimensao: 'DN 60 mm',
        classe: '15',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 52.42,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-pvc-pba-75.jpg',
        codigo: '5401000638',
        busca: 'tubo',
        nome: 'Tubo PVC PBA JE DN 75 mm classe 20',
        material: 'PVC PBA',
        dimensao: 'DN 75 mm',
        classe: '20',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 134.61,
        cor: 'marrom',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-ocre-100.jpg',
        codigo: '5401000916',
        busca: 'tubo',
        nome: 'Tubo PVC ocre liso DN 100 mm',
        material: 'PVC',
        dimensao: 'DN 100 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6 m)',
        valor: 211.00,
        cor: 'ocre',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/tubo-ocre-150.jpg',
        codigo: '5401000509',
        busca: 'tubo',
        nome: 'Tubo PVC ocre liso DN 150 mm',
        material: 'PVC',
        dimensao: 'DN 150 mm',
        classe: ' ',
        norma: ' ',
        marca: 'Fenix',
        unidade: 'barra (6m)',
        valor: 161.50,
        cor: 'ocre',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-borboleta-tipo-wafer-dn150.jpg',
        codigo: '5401002549',
        busca: 'valvula',
        nome: 'Válvula borboleta tipo wafer DN 150 mm PN 10',
        material: 'ferro fundido',
        dimensao: '150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'VARB',
        unidade: 'unidade',
        valor: 506.30,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001980',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera DN 1/2"',
        material: 'Latão',
        dimensao: 'DN 1/2"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 19.07,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001983',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera DN 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 26.10,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-esfera.jpg',
        codigo: '5401001979',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo esfera DN 1"',
        material: 'Latão',
        dimensao: 'DN 1"',
        classe: ' ',
        norma: ' ',
        marca: 'Gip',
        unidade: 'peça',
        valor: 43.57,
        cor: ' ',
        fornecedor: 'J. E. Materiais',
        cidade: 'Ribeirão Preto - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-gaveta-cunha-borracha-bolsa-50.jpg',
        codigo: '5401002557',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha com bolsas DN 50 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: 'DN 50 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 385.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/Valvula-gaveta-cunha-borracha-flangeada-100.jpg',
        codigo: '5401002004',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 100 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: 'DN 100 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 550.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-bloqueio-gaveta-cunha-borracha-flageada-150.jpg',
        codigo: '5401002006',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 150 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: 'DN 150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 1073.33,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/Valvula-gaveta-cunha-borracha-flangeada-200.jpg',
        codigo: '5401003411',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta cunha de borracha flangeda DN 200 mm PN 10"',
        material: 'Ferro fundido',
        dimensao: 'DN 200 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'Goodsteel',
        unidade: 'peça',
        valor: 1400.00,
        cor: 'azul',
        fornecedor: 'Startubo',
        cidade: 'Santa Bárbara DOeste - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-gaveta-roscavel.jpg',
        codigo: '5401002353',
        busca: 'valvula',
        nome: 'Válvula de bloqueio tipo gaveta roscável DN 3/4"',
        material: 'Latão',
        dimensao: 'DN 3/4"',
        classe: ' ',
        norma: ' ',
        marca: 'Remadi',
        unidade: 'unidade',
        valor: 29.40,
        cor: ' ',
        fornecedor: 'Talentos D Agua',
        cidade: 'Joinville - SC',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-retencao-portinhola-dupla.jpg',
        codigo: '5401001188',
        busca: 'valvula',
        nome: 'Válvula de retenção portinhola dupla DN 100 mm',
        material: 'ferro fundido',
        dimensao: 'DN 100 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'VARB',
        unidade: 'peça',
        valor: 495.92,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-retencao-portinhola-dupla.jpg',
        codigo: '5401001189',
        busca: 'valvula',
        nome: 'Válvula de retenção portinhola dupla DN 150 mm',
        material: 'ferro fundido',
        dimensao: 'DN 150 mm',
        classe: 'PN 10',
        norma: ' ',
        marca: 'VARB',
        unidade: 'peça',
        valor: 788.42,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    },

    {
        foto: './img/valvula-retencao-portinhola-dupla.jpg',
        codigo: '5401001186',
        busca: 'valvula',
        nome: 'Válvula de retenção portinhola dupla DN 400 mm',
        material: 'ferro fundido',
        dimensao: 'DN 400 mm',
        classe: 'PN 10 / PN 16',
        norma: ' ',
        marca: 'VARB',
        unidade: 'peça',
        valor: 6074.24,
        cor: 'azul',
        fornecedor: 'VARB Automação',
        cidade: 'Piracicaba - SP',
        prazo: '30 dias',
        vigencia: '24/05/2025',
        gestor: 'Diretor Operacional'
    }

]

function carregarLista() {
    let conteudo = document.getElementById('conteudo');

    for(let i = 0; i < hidraulico.length; i++){
        conteudo.innerHTML += `<div>
                                <img src=${hidraulico[i].foto}>
                                <p>Cod.: <strong>${hidraulico[i].codigo}</strong>
                                <br>${hidraulico[i].nome}
                                <br>Material: ${hidraulico[i].material}
                                <br>Medida: ${hidraulico[i].dimensao}
                                <br>Classe: ${hidraulico[i].classe}
                                <br>Norma: ${hidraulico[i].norma}
                                <br>Marca: ${hidraulico[i].marca}
                                <br>Unidade: ${hidraulico[i].unidade}
                                <br>Preço: ${hidraulico[i].valor.toLocaleString('pt-br', {style: 'currency', currency: 'BRL'})}
                                <br>Fornecedor: ${hidraulico[i].fornecedor}
                                </p>
                                </div>`;
    }
}
